import { createContext } from 'react';
import { TranslateContextType } from './types';

export const TranslateContext = createContext<TranslateContextType>({
  t: (text: string) => text,
  setTranslations: () => {},
});

export const basicTranslations: Record<string, string> = {
  hello: 'hola',
  mom: 'mama',
  login: 'login',
  home: 'casa',
  start: 'inicio',
  follow: 'seguir',
  explore: 'explorar',
  subscribe: 'suscribirse',
  buy: 'comprar',
  next: 'siguiente',
  last: 'ultimo',
  back: 'atras',
  search: 'buscar',
  sell: 'vender',
  description: 'descripcion',
  about: 'acerca',
  live: 'en vivo',
  direct: 'directo',
  profile: 'perfil',
  messages: 'mensajes',
  send: 'enviar',
  more: 'mas',
  notifications: 'notificaciones',
  trending: 'tendencia',
  show: 'mostrar',
  see: 'ver',
  image: 'imagen',
  like: 'me gusta',
  comment: 'comentar',
  views: 'vistas',
  process: 'proceso',
  loading: 'cargando',
  question: 'pregunta',
  questions: 'preguntas',
  frequently: 'frecuentemente',
  ask: 'preguntar',
  asked: 'preguntado',
  after: 'despues',
  before: 'antes',
  dislike: 'no me gusta',
  arrives: 'llega',
  arrive: 'llegar',
  end: 'fin',
  better: 'mejor',
  worse: 'peor',
  return: 'volver',
  build: 'construir',
  enter: 'entrar',
  account: 'cuenta',
  dark: 'oscuro',
  light: 'luz',
  mode: 'modo',
  empty: 'vaciar',
  table: 'tabla',
  button: 'boton',
  element: 'elemento',
  my: 'mi',
  text: 'texto',
  translated: 'traducido',
  allow: 'permitir',
};
